### ISSUE TITLE
Errr from ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent

### ISSUE THREAD

**Issue by atmohsin** [NaikSoftware/StompProtocolAndroid#73] opened 2017-09-19 11:05 UTC
Hi 

We are getting following exception while connecting to the server. Please let know if there is any issue, is there any work around. 

java.lang.NullPointerException: Attempt to invoke virtual method 'void rx.Subscriber.onNext(java.lang.Object)' on a null object reference
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:150)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:115)
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:252)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:762)

************ DEVICE INFORMATION ***********
Brand: samsung
Device: dream2lte
Model: SM-G955F
Id: NRD90M
Product: dream2ltexx

************ FIRMWARE ************
SDK: 24
Release: 7.0
Incremental: G955FXXU1AQH3

**Comment by forresthopkinsa** [comment] 2017-09-21 15:59
Can you post the code that's throwing the exception?

**Comment by atmohsin** [comment] 2017-09-22 07:07
We trying to figure out from where our code this exception. This happened some device.  We got the stacktrace from the user. Our code base is not showing. It is showing from the liberary. 

With this exception our app getting crashed and getting closed. It seems some null value, because of this the exception. Do we need to have null check or some work around, so that app wont get crashed.

Thanks
Mohsin

**Comment by forresthopkinsa** [comment] 2017-09-22 17:10
Wait, so you're not able to _reproduce_ the exception yourself? That certainly makes things more difficult. I'll look into it, let me know when you figure out how to reproduce the error.

**Comment by forresthopkinsa** [comment] 2017-09-22 17:19
My best guess is that you're using **version 1.2.2**, in which case, your user is almost definitely rotating the screen, causing issue #61 . Fortunately, this has already been fixed, so if you start pushing the latest release, you shouldn't face this issue anymore.

**Comment by atmohsin** [comment] 2017-09-23 18:45
Hi 

Thanks for the replay, The issue is coming in one of the device the client is using. Samsung Edge. 

We are using latest version.

Now client is getting now below exception. 

java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:153)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:117)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:192)
	at java.lang.Thread.run(Thread.java:762)

**Comment by forresthopkinsa** [comment] 2017-09-25 15:58
First, try to repro this issue yourself so we're not relying on bug reports from your clients. You should be able to do it by rotating your screen.

Then, try the solution offered by Steviemo in the thread of the other issue:

>Was able to get around this issue by removing:
>
>``` java
>.subscribeOn(Schedulers.io())
>.observeOn(AndroidSchedulers.mainThread())
>```

And see if that changes anything.

**Comment by forresthopkinsa** [comment] 2017-09-29 22:48
Did that solution work? If it didn't, please be sure to report back with how you got it to work, so that anyone else who faces that problem in the future can learn from your experience.

**Comment by atmohsin** [comment] 2017-10-03 09:58
Hi,
We implemented the work around, We tested it in samsung cloud remote lab, It worked, When we release the app to the client for some time it worked. 

Now they are still getting same issue.  

Please suggest any solutions for this.

This is the latest stack trace which we got

java.lang.NullPointerException: Attempt to invoke interface method 'void io.reactivex.FlowableEmitter.onNext(java.lang.Object)' on a null object reference
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.emitLifecycleEvent(WebSocketsConnectionProvider.java:153)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider.access$200(WebSocketsConnectionProvider.java:30)
	at ua.naiksoftware.stomp.WebSocketsConnectionProvider$1.onError(WebSocketsConnectionProvider.java:117)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:236)
	at java.lang.Thread.run(Thread.java:762)

Thanks
Mohsin

**Comment by forresthopkinsa** [comment] 2017-10-03 18:38
Once again, I have to ask: can you reproduce the error yourself? If you can't reproduce it, then it's not our turn to work with it yet; it's still in your hands.

**Comment by atmohsin** [comment] 2017-10-09 07:49
We are able to reproduce this issue. It comes in Samsung Edge mobile phone.  

What is the best way to solve this issue. 

Thanks
Mohsin

**Comment by forresthopkinsa** [comment] 2017-10-09 19:16
What are the steps that you can follow to reproduce it? Start to finish. Does it happen when rotating the phone? Does it happen when subscribed or unsubscribed? What triggers it?

Also, please paste the relevant code, and do it in Github code block format, which looks like this:

\``` java
\<code here>
\```

**Comment by NaikSoftware** [comment] 2017-12-26 11:48
Fixed in 1.4.4

**Closed by NaikSoftware** 2017-12-26 11:48 UTC
